[package]
name = "testbin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bp3d-os = { path = "../core", features = ["open", "fs", "dirs", "assets"] }
