name: Release

on:
  push:
    branches:
      - master

jobs:
  Publish:
    uses: BlockProject3D/workflows/.github/workflows/Publish.yml@main
    with:
      cwd: core
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
